version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: "0"
    ENVIRONMENT: "dev"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "=== Installing Dependencies ==="
      - pip install --upgrade pip
      - pip install aws-sam-cli

  pre_build:
    commands:
      - echo "=== Pre-Build Phase ==="
      - ls -la
      - ls -la FHIR/

  build:
    commands:
      - echo "=== Build Phase ==="
      - cd FHIR
      - sam build --template-file hoth_migration_components.yaml
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file ../packaged-template.yaml --resolve-s3
      - cd ..
      
      # Copy config files to root for artifacts
      - echo "=== Copying config files ==="
      - cp FHIR/dev.json . 2>/dev/null || echo "dev.json not found in FHIR/"
      - cp FHIR/test.json . 2>/dev/null || echo "test.json not found in FHIR/"
      - cp FHIR/prod.json . 2>/dev/null || echo "prod.json not found in FHIR/"
      
      # List files to verify
      - echo "=== Files in root ==="
      - ls -la *.json 2>/dev/null || echo "No JSON files found"
      - ls -la packaged-template.yaml

  post_build:
    commands:
      - echo "=== Build Complete ==="

artifacts:
  files:
    - packaged-template.yaml
    - dev.json
    - test.json
    - prod.json
  discard-paths: yes