version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: "0"
    ENVIRONMENT: "dev"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "=== Installing Dependencies ==="
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo "=== Pre-Build Phase ==="
      - echo "Current directory:" && pwd
      - echo "Listing files:" && ls -la
      - echo "FHIR directory:" && ls -la FHIR/

  build:
    commands:
      - echo "=== Build Phase ==="
      - cd FHIR
      - echo "Current directory:" && pwd
      
      # Build SAM application
      - echo "Running sam build..."
      - sam build --template-file hoth_migration_components.yaml --debug || { echo "SAM BUILD FAILED"; exit 1; }
      
      # Check build output exists
      - echo "Checking build output..."
      - ls -la .aws-sam/build/ || { echo "Build output not found"; exit 1; }
      
      # Package with auto-managed S3 bucket
      - echo "Running sam package..."
      - sam package --template-file .aws-sam/build/template.yaml --output-template-file ../packaged-template.yaml --resolve-s3 || { echo "SAM PACKAGE FAILED"; exit 1; }
      
      - cd ..
      - echo "Packaged template:" && ls -la packaged-template.yaml

  post_build:
    commands:
      - echo "=== Post-Build Phase ==="
      - echo "Build completed successfully!"

artifacts:
  files:
    - packaged-template.yaml
  discard-paths: yes