AWSTemplateFormatVersion: '2010-09-09'
Description: |
  FHIR Migration Secrets Manager Configuration
  Stores application secrets and Okta configuration for token validation

Parameters:
  Environment:
    Type: String
    Description: Deployment environment

  ApplicationName:
    Type: String
    Description: Project name for resource naming
    Default: hoth-data-application

  OktaDomain:
    Type: String
    Description: Okta domain for token verification
    Default: your-okta-domain.okta.com

Resources:
  #############################################
  # Main Application Secret
  #############################################
  FhirMigrationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ApplicationName}/fhir-migration/${Environment}'
      Description: Configuration secrets for FHIR migration application
      SecretString: !Sub |
        {
          "database_host": "placeholder-update-after-deployment",
          "database_port": "5432",
          "database_name": "fhir_migration_db",
          "database_username": "admin",
          "database_password": "placeholder-update-after-deployment",
          "api_key": "placeholder-update-after-deployment",
          "encryption_key": "placeholder-update-after-deployment",
          "environment": "${Environment}"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation

  # Resource policy for the main secret
  FhirMigrationSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref FhirMigrationSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: EnableLambdaAccess
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - 'secretsmanager:GetSecretValue'
            Resource: '*'
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId

  #############################################
  # Okta Configuration Secret
  #############################################
  OktaConfigSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ApplicationName}/okta-config/${Environment}'
      Description: Okta configuration for API Gateway token validation
      SecretString: !Sub |
        {
          "client_id": "placeholder-update-after-deployment",
          "client_secret": "placeholder-update-after-deployment",
          "issuer": "https://${OktaDomain}/oauth2/default",
          "audience": "api://${ApplicationName}",
          "domain": "${OktaDomain}",
          "required_scopes": ["openid", "profile"],
          "token_endpoint": "https://${OktaDomain}/oauth2/default/v1/token",
          "introspect_endpoint": "https://${OktaDomain}/oauth2/default/v1/introspect",
          "jwks_uri": "https://${OktaDomain}/oauth2/default/v1/keys"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation

  # Resource policy for Okta secret
  OktaConfigSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref OktaConfigSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: EnableLambdaAccess
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - 'secretsmanager:GetSecretValue'
            Resource: '*'
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref AWS::AccountId

  #############################################
  # Glue Job Secrets
  #############################################
  GlueJobSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ApplicationName}/glue-config/${Environment}'
      Description: Configuration for Glue ETL jobs
      SecretString: !Sub |
        {
          "source_connection_string": "placeholder-update-after-deployment",
          "target_connection_string": "placeholder-update-after-deployment",
          "s3_bucket": "${ApplicationName}-data-${Environment}",
          "encryption_key": "placeholder-update-after-deployment",
          "environment": "${Environment}"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation

  #############################################
  # Secret Rotation Schedule (Optional)
  #############################################
  # Uncomment to enable automatic rotation
  # FhirMigrationSecretRotationSchedule:
  #   Type: AWS::SecretsManager::RotationSchedule
  #   DependsOn: FhirMigrationSecretResourcePolicy
  #   Properties:
  #     SecretId: !Ref FhirMigrationSecret
  #     RotationRules:
  #       AutomaticallyAfterDays: 30
  #     RotationLambdaARN: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SecretsRotationFunction'

Outputs:
  FhirMigrationSecretArn:
    Description: ARN of the FHIR migration secret
    Value: !Ref FhirMigrationSecret
    Export:
      Name: !Sub '${ApplicationName}-FhirMigrationSecretArn-${Environment}'

  FhirMigrationSecretName:
    Description: Name of the FHIR migration secret
    Value: !Sub '${ApplicationName}/fhir-migration/${Environment}'
    Export:
      Name: !Sub '${ApplicationName}-FhirMigrationSecretName-${Environment}'

  OktaConfigSecretArn:
    Description: ARN of the Okta configuration secret
    Value: !Ref OktaConfigSecret
    Export:
      Name: !Sub '${ApplicationName}-OktaConfigSecretArn-${Environment}'

  OktaConfigSecretName:
    Description: Name of the Okta configuration secret
    Value: !Sub '${ApplicationName}/okta-config/${Environment}'
    Export:
      Name: !Sub '${ApplicationName}-OktaConfigSecretName-${Environment}'

  GlueJobSecretArn:
    Description: ARN of the Glue job configuration secret
    Value: !Ref GlueJobSecret
    Export:
      Name: !Sub '${ApplicationName}-GlueJobSecretArn-${Environment}'
